<?php

// Implements hook_block_info()
function hf_stacks_search_block_info() {
    $blocks['hf_stacks_search_block'] = array(
      'info' => 'Stacks Search',
      'cache' => DRUPAL_NO_CACHE,
      'status' => 1,
      'visibility' => BLOCK_VISIBILITY_NOTLISTED,
      'region' => 'header',
    );
    return $blocks;
}

// Implements hook_block_configure()
function hf_stacks_search_block_configure($delta = '') {
  $form['catalogue_url_wrap'] = array(
    '#type' => 'fieldset',
    '#title' => t('Catalogue Search'),
    '#collapsible' => FALSE,
  );

  $form['catalogue_url_wrap']['catalogue_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Catalogue Search Base URL'),
    '#size' => 60,
    '#required' => TRUE,
    '#default_value' => variable_get('hf_stacks_search_catalogue_url'),
    '#description' => t('URL which the catalogue goes to.'),
  );

  $form['catalogue_url_wrap']['catalogue_ctx'] = array(
    '#type' => 'textfield',
    '#title' => t('Querystring CTX'),
    '#size' => 60,
    '#required' => TRUE,
    '#default_value' => variable_get('hf_stacks_search_catalogue_ctx'),
    //'#description' => t('URL which the catalogue goes to.'),
  );

  $form['catalogue_url_wrap']['catalogue_tom'] = array(
    '#type' => 'textfield',
    '#title' => t('Querystring TOM'),
    '#size' => 60,
    '#required' => TRUE,
    '#default_value' => variable_get('hf_stacks_search_catalogue_tom'),
    //'#description' => t('URL which the catalogue goes to.'),
  );

  $form['catalogue_url_wrap']['catalogue_page'] = array(
    '#type' => 'textfield',
    '#title' => t('Querystring Page'),
    '#size' => 60,
    '#required' => TRUE,
    '#default_value' => variable_get('hf_stacks_search_catalogue_page'),
    //'#description' => t('URL which the catalogue goes to.'),
  );

  $form['advanced_url_wrap'] = array(
    '#type' => 'fieldset',
    '#title' => t('Advanced Search'),
    '#collapsible' => FALSE,
  );

  $form['advanced_url_wrap']['advanced_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Advanced Search URL'),
    '#size' => 60,
    '#required' => TRUE,
    '#default_value' => variable_get('hf_stacks_search_advanced_url'),
    '#description' => t('URL which the Advanced Search goes to.'),
  );

  return $form;
}

// Implementation of hook_block_save()
function hf_stacks_search_block_save($delta = '', $edit = array()){
  variable_set('hf_stacks_search_catalogue_url', $edit['catalogue_url']);
  variable_set('hf_stacks_search_catalogue_ctx', $edit['catalogue_ctx']);
  variable_set('hf_stacks_search_catalogue_tom', $edit['catalogue_tom']);
  variable_set('hf_stacks_search_catalogue_page', $edit['catalogue_page']);
  variable_set('hf_stacks_search_advanced_url', $edit['advanced_url']);
}

// Implementation of hook_block_view()
function hf_stacks_search_block_view($delta = '') {
  global $base_path;

  $user_role = $GLOBALS['user']->roles;
  if (in_array("patron", $user_role)) {
    $user_role = "patron";
  }

  // EDS Native 1
  $native_auth_type = '';
  if ( ($user_role == 'patron') && (variable_get('stacks_search_edsnative_sso') == '1') ) {
    $native_auth_type = 'sso';
  } elseif ( ($user_role == 'patron') && ( (variable_get('stacks_search_edsnative_sso') == '1') || (empty(variable_get('stacks_search_edsnative_sso'))) ) ) {
    $native_auth_type = 'uid';
  } else {
    if (variable_get('stacks_search_edsnative_guest') == '1') { $native_auth_type = 'ip,guest'; }
  }
  if (variable_get('stacks_search_edsnative_uid') == '1') { $native_auth_type = 'uid'; }
  if (variable_get('stacks_search_edsnative_athens') == '1') { $native_auth_type = 'athens'; }

  // EDS Native 2
  $native_auth_type2 = '';
  if ( ($user_role == 'patron') && (variable_get('stacks_search_edsnative_sso2') == '1') ) {
    $native_auth_type2 = 'sso';
  } elseif ( ($user_role == 'patron') && ( (variable_get('stacks_search_edsnative_sso2') == '1') || (empty(variable_get('stacks_search_edsnative_sso2'))) ) ) {
    $native_auth_type2 = 'uid';
  } else {
    if (variable_get('stacks_search_edsnative_guest2') == '1') { $native_auth_type2 = 'ip,guest'; }
  }
  if (variable_get('stacks_search_edsnative_uid2') == '1') { $native_auth_type2 = 'uid'; }
  if (variable_get('stacks_search_edsnative_athens2') == '1') { $native_auth_type2 = 'athens'; }

  // EDS Native 3
  $native_auth_type3 = '';
  if ( ($user_role == 'patron') && (variable_get('stacks_search_edsnative_sso3') == '1') ) {
    $native_auth_type3 = 'sso';
  } elseif ( ($user_role == 'patron') && ( (variable_get('stacks_search_edsnative_sso3') == '1') || (empty(variable_get('stacks_search_edsnative_sso3'))) ) ) {
    $native_auth_type3 = 'uid';
  } else {
    if (variable_get('stacks_search_edsnative_guest3') == '1') { $native_auth_type3 = 'ip,guest'; }
  }
  if (variable_get('stacks_search_edsnative_uid3') == '1') { $native_auth_type3 = 'uid'; }
  if (variable_get('stacks_search_edsnative_athens3') == '1') { $native_auth_type3 = 'athens'; }

  if (!empty($_REQUEST['query'])) {
    $query = $_REQUEST['query'];
  } elseif (!empty($_REQUEST['bentoq'])) {
    $query = $_REQUEST['bentoq'];
  } else {
    $query = '';
  }

  drupal_add_js(drupal_get_path('module', 'hf_stacks_search') . '/hf_stacks_search.js');

  $stacks_search = variable_get('stacks_search', '');
  $stacks_search_internal_checkbox = variable_get('stacks_search_internal_checkbox', '');
  $stacks_search_internal_title = variable_get('stacks_search_internal_title', '');
  $stacks_search_eds_checkbox = variable_get('stacks_search_eds_checkbox', '');
  $stacks_search_eds_title = variable_get('stacks_search_eds_title', '');

  $stacks_search_external_checkbox = variable_get('stacks_search_external_checkbox', '');
  $stacks_search_external_title = variable_get('stacks_search_external_title', '');
  $stacks_search_external = variable_get('stacks_search_external', '');

  $stacks_search_external_checkbox_2 = variable_get('stacks_search_external_checkbox_2', '');
  $stacks_search_external_title_2 = variable_get('stacks_search_external_title_2', '');
  $stacks_search_external_2 = variable_get('stacks_search_external_2', '');

  $stacks_search_external_checkbox_3 = variable_get('stacks_search_external_checkbox_3', '');
  $stacks_search_external_title_3 = variable_get('stacks_search_external_title_3', '');
  $stacks_search_external_3 = variable_get('stacks_search_external_3', '');

  $stacks_search_bento_checkbox = variable_get('stacks_search_bento_checkbox', '');
  $stacks_search_bento_title = variable_get('stacks_search_bento_title', '');

  $stacks_url = current_path();
  //dpm($stacks_url);

  $catalogOptions = '';
  if ($stacks_search_eds_checkbox == '1') {
    if (!empty($stacks_search_eds_title)) {
      $catalogOptions .= "<option value='eds'";
      if ( (($stacks_search == 'eds') && ($stacks_url == 'homepage')) || ($stacks_url == 'eds') || (($stacks_search == 'eds') && ($stacks_url != 'multisearch') && ($stacks_url != 'solr') && ($stacks_url != 'homepage')) ) {
        $catalogOptions .= " selected";
      }
      $catalogOptions .= ">".$stacks_search_eds_title."</option>";
    } else {
      $catalogOptions .= "<option value='eds'";
      if ( (($stacks_search == 'eds') && ($stacks_url == 'homepage')) || ($stacks_url == 'eds') || (($stacks_search == 'eds') && ($stacks_url != 'multisearch') && ($stacks_url != 'solr') && ($stacks_url != 'homepage')) ) {
        $catalogOptions .= " selected";
      }
      $catalogOptions .= ">Resources</option>";
    }
  }
  if ($stacks_search_external_checkbox == '1') {
    if (!empty($stacks_search_external_title)) {
      $catalogOptions .= "<option value='ext'";
      if ( (($stacks_search == 'external') && ($stacks_url == 'homepage')) || (($stacks_search == 'external') && ($stacks_url != 'eds') && ($stacks_url != 'multisearch') && ($stacks_url != 'solr') && ($stacks_url != 'homepage')) ) {
        $catalogOptions .= " selected";
      }
      $catalogOptions .= ">".$stacks_search_external_title."</option>";
    } else {
      $catalogOptions .= "<option value='ext'";
      if ( (($stacks_search == 'external') && ($stacks_url == 'homepage')) || (($stacks_search == 'external') && ($stacks_url != 'eds') && ($stacks_url != 'multisearch') && ($stacks_url != 'solr') && ($stacks_url != 'homepage')) ) {
        $catalogOptions .= " selected";
      }
      $catalogOptions .= ">Catalog</option>";
    }
  }
  if ($stacks_search_external_checkbox_2 == '1') {
    if (!empty($stacks_search_external_title_2)) {
      $catalogOptions .= "<option value='ext2'";
      if ( (($stacks_search == 'external_2') && ($stacks_url == 'homepage')) || (($stacks_search == 'external') && ($stacks_url != 'eds') && ($stacks_url != 'multisearch') && ($stacks_url != 'solr') && ($stacks_url != 'homepage')) ) {
        $catalogOptions .= " selected";
      }
      $catalogOptions .= ">".$stacks_search_external_title_2."</option>";
    } else {
      $catalogOptions .= "<option value='ext2'";
      if ( (($stacks_search == 'external_2') && ($stacks_url == 'homepage')) || (($stacks_search == 'external') && ($stacks_url != 'eds') && ($stacks_url != 'multisearch') && ($stacks_url != 'solr') && ($stacks_url != 'homepage')) ) {
        $catalogOptions .= " selected";
      }
      $catalogOptions .= ">Catalog</option>";
    }
  }
  if ($stacks_search_external_checkbox_3 == '1') {
    if (!empty($stacks_search_external_title_3)) {
      $catalogOptions .= "<option value='ext3'";
      if ( (($stacks_search == 'external_3') && ($stacks_url == 'homepage')) || (($stacks_search == 'external') && ($stacks_url != 'eds') && ($stacks_url != 'multisearch') && ($stacks_url != 'solr') && ($stacks_url != 'homepage')) ) {
        $catalogOptions .= " selected";
      }
      $catalogOptions .= ">".$stacks_search_external_title_3."</option>";
    } else {
      $catalogOptions .= "<option value='ext3'";
      if ( (($stacks_search == 'external_3') && ($stacks_url == 'homepage')) || (($stacks_search == 'external') && ($stacks_url != 'eds') && ($stacks_url != 'multisearch') && ($stacks_url != 'solr') && ($stacks_url != 'homepage')) ) {
        $catalogOptions .= " selected";
      }
      $catalogOptions .= ">Catalog</option>";
    }
  }
  if ($stacks_search_internal_checkbox == '1') {
    if (!empty($stacks_search_internal_title)) {
      $catalogOptions .= "<option value='web'";
      if ( (($stacks_search == 'internal') && ($stacks_url == 'homepage')) || ($stacks_url == 'solr') || (($stacks_search == 'internal') && ($stacks_url != 'eds') && ($stacks_url != 'multisearch') && ($stacks_url != 'homepage')) ) {
        $catalogOptions .= " selected";
      }
      $catalogOptions .= ">".$stacks_search_internal_title."</option>";
    } else {
      $catalogOptions .= "<option value='web'";
      if ( (($stacks_search == 'internal') && ($stacks_url == 'homepage')) || ($stacks_url == 'solr') || (($stacks_search == 'internal') && ($stacks_url != 'eds') && ($stacks_url != 'multisearch') && ($stacks_url != 'homepage')) ) {
        $catalogOptions .= " selected";
      }
      $catalogOptions .= ">Website</option>";
    }
  }
  if ($stacks_search_bento_checkbox == '1') {
    if(!empty($stacks_search_bento_title)) {
      $catalogOptions .= "<option value='bento'";
      if ( (($stacks_search == 'bento') && ($stacks_url == 'homepage')) || ($stacks_url == 'multisearch') || (($stacks_search == 'bento') && ($stacks_url != 'eds') && ($stacks_url != 'solr') && ($stacks_url != 'homepage')) ) {
        $catalogOptions .= " selected";
      }
      $catalogOptions .= ">". $stacks_search_bento_title . "</option>";
    } else {
      $catalogOptions .= "<option value='bento'";
      if ( (($stacks_search == 'bento') && ($stacks_url == 'homepage')) || ($stacks_url == 'multisearch') || (($stacks_search == 'bento') && ($stacks_url != 'eds') && ($stacks_url != 'solr') && ($stacks_url != 'homepage')) ) {
        $catalogOptions .= " selected";
      }
      $catalogOptions .= ">Bento</option>";
    }
  }

  $catalogue_url = '';
  
  if ($stacks_search_external == 'polaris') {
    if (module_exists('domain_conf')) {
      $domain = domain_get_domain();

      $catalogue_url = domain_conf_variable_get($domain['domain_id'], 'stacks_search_polaris_opac_url');
    } else {
      $catalogue_url = variable_get('stacks_search_polaris_opac_url');
    }
  } elseif ($stacks_search_external == 'edsnative') {
    if (module_exists('domain_conf')) {
      $domain = domain_get_domain();
      $catalogue_url = domain_conf_variable_get($domain['domain_id'], 'stacks_search_edsnative_catalogue_url');
    } else {
      $catalogue_url = variable_get('stacks_search_edsnative_catalogue_url');
    }
  } elseif ($stacks_search_external == 'iii') {
    if (module_exists('domain_conf')) {
      $domain = domain_get_domain();
      $catalogue_url = domain_conf_variable_get($domain['domain_id'], 'stacks_search_iii_catalogue_url ');
    } else {
      $catalogue_url = variable_get('stacks_search_iii_catalogue_url');
    }
  } elseif ($stacks_search_external == 'sirsi') {
    if (module_exists('domain_conf')) {
      $domain = domain_get_domain();
      $catalogue_url = domain_conf_variable_get($domain['domain_id'], 'stacks_search_sirsi_opac_url');
    } else {
      $catalogue_url = variable_get('stacks_search_sirsi_opac_url');
    }
  } elseif ($stacks_search_external == 'evergreen') {
    if (module_exists('domain_conf')) {
      $domain = domain_get_domain();
      $catalogue_url = domain_conf_variable_get($domain['domain_id'], 'stacks_search_evergreen_catalogue_url');
    } else {
      $catalogue_url = variable_get('stacks_search_evergreen_catalogue_url');
    }
  } elseif ($stacks_search_external == 'oclc') {
    if (module_exists('domain_conf')) {
      $domain = domain_get_domain();
      $catalogue_url = domain_conf_variable_get($domain['domain_id'], 'stacks_search_oclc_catalogue_url');
    } else {
      $catalogue_url = variable_get('stacks_search_oclc_catalogue_url');
    }
  } elseif ($stacks_search_external == 'edsnative') {
    if (module_exists('domain_conf')) {
      $domain = domain_get_domain();
      $catalogue_url = domain_conf_variable_get($domain['domain_id'], 'stacks_search_edsnative_catalogue_url');
    } else {
      $catalogue_url = variable_get('stacks_search_edsnative_catalogue_url');
    }
  } elseif ($stacks_search_external == 'edsnative2') {
    if (module_exists('domain_conf')) {
      $domain = domain_get_domain();
      $catalogue_url = domain_conf_variable_get($domain['domain_id'], 'stacks_search_edsnative_catalogue_url2');
    } else {
      $catalogue_url = variable_get('stacks_search_edsnative_catalogue_url2');
    }
  } elseif ($stacks_search_external == 'edsnative3') {
    if (module_exists('domain_conf')) {
      $domain = domain_get_domain();
      $catalogue_url = domain_conf_variable_get($domain['domain_id'], 'stacks_search_edsnative_catalogue_url3');
    } else {
      $catalogue_url = variable_get('stacks_search_edsnative_catalogue_url3');
    }
  } elseif ($stacks_search_external == 'koha') {
    if (module_exists('domain_conf')) {
      $domain = domain_get_domain();
      $catalogue_url = domain_conf_variable_get($domain['domain_id'], 'stacks_search_koha_catalogue_url');
    } else {
      $catalogue_url = variable_get('stacks_search_koha_catalogue_url');
    }
  } elseif ($stacks_search_external == 'exlibris') {
    if (module_exists('domain_conf')) {
      $domain = domain_get_domain();
      $catalogue_url = domain_conf_variable_get($domain['domain_id'], 'stacks_search_exlibris_catalogue_url');
    } else {
      $catalogue_url = variable_get('stacks_search_exlibris_catalogue_url');
    }
  } elseif ($stacks_search_external == 'bibliocommons') {
    if (module_exists('domain_co233nf')) {
      $domain = domain_get_domain();
      $catalogue_url = domain_conf_variable_get($domain['domain_id'], 'stacks_search_bibliocommons_catalogue_url');
    } else {
      $catalogue_url = variable_get('stacks_search_bibliocommons_catalogue_url');
    }
  } elseif ($stacks_search_external == 'vufind') {
    if (module_exists('domain_conf')) {
      $domain = domain_get_domain();
      $catalogue_url = domain_conf_variable_get($domain['domain_id'], 'stacks_search_vufind_catalogue_url');
    } else {
      $catalogue_url = variable_get('stacks_search_vufind_catalogue_url');
    }
  }

  $catalogue_url_2 = '';

  if ($stacks_search_external_2 == 'polaris') {
    if (module_exists('domain_conf')) {
      $domain = domain_get_domain();

      $catalogue_url_2 = domain_conf_variable_get($domain['domain_id'], 'stacks_search_polaris_opac_url');
    } else {
      $catalogue_url_2 = variable_get('stacks_search_polaris_opac_url');
    }
  } elseif ($stacks_search_external_2 == 'edsnative') {
    if (module_exists('domain_conf')) {
      $domain = domain_get_domain();
      $catalogue_url_2 = domain_conf_variable_get($domain['domain_id'], 'stacks_search_edsnative_catalogue_url');
    } else {
      $catalogue_url_2 = variable_get('stacks_search_edsnative_catalogue_url');
    }
  } elseif ($stacks_search_external_2 == 'edsnative2') {
    if (module_exists('domain_conf')) {
      $domain = domain_get_domain();
      $catalogue_url_2 = domain_conf_variable_get($domain['domain_id'], 'stacks_search_edsnative_catalogue_url2');
    } else {
      $catalogue_url_2 = variable_get('stacks_search_edsnative_catalogue_url2');
    }
  } elseif ($stacks_search_external_2 == 'edsnative3') {
    if (module_exists('domain_conf')) {
      $domain = domain_get_domain();
      $catalogue_url_2 = domain_conf_variable_get($domain['domain_id'], 'stacks_search_edsnative_catalogue_url3');
    } else {
      $catalogue_url_2 = variable_get('stacks_search_edsnative_catalogue_url3');
    }
  } elseif ($stacks_search_external_2 == 'iii') {
    if (module_exists('domain_conf')) {
      $domain = domain_get_domain();
      $catalogue_url_2 = domain_conf_variable_get($domain['domain_id'], 'stacks_search_iii_catalogue_url ');
    } else {
      $catalogue_url_2 = variable_get('stacks_search_iii_catalogue_url');
    }
  } elseif ($stacks_search_external_2 == 'sirsi') {
    if (module_exists('domain_conf')) {
      $domain = domain_get_domain();
      $catalogue_url_2 = domain_conf_variable_get($domain['domain_id'], 'stacks_search_sirsi_opac_url');
    } else {
      $catalogue_url_2 = variable_get('stacks_search_sirsi_opac_url');
    }
  } elseif ($stacks_search_external_2 == 'evergreen') {
    if (module_exists('domain_conf')) {
      $domain = domain_get_domain();
      $catalogue_url_2 = domain_conf_variable_get($domain['domain_id'], 'stacks_search_evergreen_catalogue_url');
    } else {
      $catalogue_url_2 = variable_get('stacks_search_evergreen_catalogue_url');
    }
  } elseif ($stacks_search_external_2 == 'oclc') {
    if (module_exists('domain_conf')) {
      $domain = domain_get_domain();
      $catalogue_url_2 = domain_conf_variable_get($domain['domain_id'], 'stacks_search_oclc_catalogue_url');
    } else {
      $catalogue_url_2 = variable_get('stacks_search_oclc_catalogue_url');
    }
  } elseif ($stacks_search_external_2 == 'edsnative') {
    if (module_exists('domain_conf')) {
      $domain = domain_get_domain();
      $catalogue_url_2 = domain_conf_variable_get($domain['domain_id'], 'stacks_search_edsnative_catalogue_url');
    } else {
      $catalogue_url_2 = variable_get('stacks_search_edsnative_catalogue_url');
    }
  } elseif ($stacks_search_external_2 == 'koha') {
    if (module_exists('domain_conf')) {
      $domain = domain_get_domain();
      $catalogue_url_2 = domain_conf_variable_get($domain['domain_id'], 'stacks_search_koha_catalogue_url');
    } else {
      $catalogue_url_2 = variable_get('stacks_search_koha_catalogue_url');
    }
  } elseif ($stacks_search_external == 'exlibris') {
    if (module_exists('domain_conf')) {
      $domain = domain_get_domain();
      $catalogue_url_2 = domain_conf_variable_get($domain['domain_id'], 'stacks_search_exlibris_catalogue_url');
    } else {
      $catalogue_url_2 = variable_get('stacks_search_exlibris_catalogue_url');
    }
  } elseif ($stacks_search_external_2 == 'bibliocommons') {
    if (module_exists('domain_co233nf')) {
      $domain = domain_get_domain();
      $catalogue_url_2 = domain_conf_variable_get($domain['domain_id'], 'stacks_search_bibliocommons_catalogue_url');
    } else {
      $catalogue_url_2 = variable_get('stacks_search_bibliocommons_catalogue_url');
    }
  } elseif ($stacks_search_external_2 == 'vufind') {
    if (module_exists('domain_conf')) {
      $domain = domain_get_domain();
      $catalogue_url_2 = domain_conf_variable_get($domain['domain_id'], 'stacks_search_vufind_catalogue_url');
    } else {
      $catalogue_url_2 = variable_get('stacks_search_vufind_catalogue_url');
    }
  }

  $catalogue_url_3 = '';

  if ($stacks_search_external_3 == 'polaris') {
    if (module_exists('domain_conf')) {
      $domain = domain_get_domain();

      $catalogue_url_3 = domain_conf_variable_get($domain['domain_id'], 'stacks_search_polaris_opac_url');
    } else {
      $catalogue_url_3 = variable_get('stacks_search_polaris_opac_url');
    }
  } elseif ($stacks_search_external_3 == 'edsnative') {
    if (module_exists('domain_conf')) {
      $domain = domain_get_domain();
      $catalogue_url_3 = domain_conf_variable_get($domain['domain_id'], 'stacks_search_edsnative_catalogue_url');
    } else {
      $catalogue_url_3 = variable_get('stacks_search_edsnative_catalogue_url');
    }
  } elseif ($stacks_search_external_3 == 'edsnative2') {
    if (module_exists('domain_conf')) {
      $domain = domain_get_domain();
      $catalogue_url_3 = domain_conf_variable_get($domain['domain_id'], 'stacks_search_edsnative_catalogue_url2');
    } else {
      $catalogue_url_3 = variable_get('stacks_search_edsnative_catalogue_url2');
    }
  } elseif ($stacks_search_external_3 == 'edsnative3') {
    if (module_exists('domain_conf')) {
      $domain = domain_get_domain();
      $catalogue_url_3 = domain_conf_variable_get($domain['domain_id'], 'stacks_search_edsnative_catalogue_url3');
    } else {
      $catalogue_url_3 = variable_get('stacks_search_edsnative_catalogue_url3');
    }
  } elseif ($stacks_search_external_3 == 'iii') {
    if (module_exists('domain_conf')) {
      $domain = domain_get_domain();
      $catalogue_url_3 = domain_conf_variable_get($domain['domain_id'], 'stacks_search_iii_catalogue_url ');
    } else {
      $catalogue_url_3 = variable_get('stacks_search_iii_catalogue_url');
    }
  } elseif ($stacks_search_external_3 == 'sirsi') {
    if (module_exists('domain_conf')) {
      $domain = domain_get_domain();
      $catalogue_url_3 = domain_conf_variable_get($domain['domain_id'], 'stacks_search_sirsi_opac_url');
    } else {
      $catalogue_url_3 = variable_get('stacks_search_sirsi_opac_url');
    }
  } elseif ($stacks_search_external_3 == 'evergreen') {
    if (module_exists('domain_conf')) {
      $domain = domain_get_domain();
      $catalogue_url_3 = domain_conf_variable_get($domain['domain_id'], 'stacks_search_evergreen_catalogue_url');
    } else {
      $catalogue_url_3 = variable_get('stacks_search_evergreen_catalogue_url');
    }
  } elseif ($stacks_search_external_3 == 'oclc') {
    if (module_exists('domain_conf')) {
      $domain = domain_get_domain();
      $catalogue_url_3 = domain_conf_variable_get($domain['domain_id'], 'stacks_search_oclc_catalogue_url');
    } else {
      $catalogue_url_3 = variable_get('stacks_search_oclc_catalogue_url');
    }
  } elseif ($stacks_search_external_3 == 'edsnative') {
    if (module_exists('domain_conf')) {
      $domain = domain_get_domain();
      $catalogue_url_3 = domain_conf_variable_get($domain['domain_id'], 'stacks_search_edsnative_catalogue_url');
    } else {
      $catalogue_url_3 = variable_get('stacks_search_edsnative_catalogue_url');
    }
  } elseif ($stacks_search_external_3 == 'koha') {
    if (module_exists('domain_conf')) {
      $domain = domain_get_domain();
      $catalogue_url_3 = domain_conf_variable_get($domain['domain_id'], 'stacks_search_koha_catalogue_url');
    } else {
      $catalogue_url_3 = variable_get('stacks_search_koha_catalogue_url');
    }
  } elseif ($stacks_search_external_3 == 'exlibris') {
    if (module_exists('domain_conf')) {
      $domain = domain_get_domain();
      $catalogue_url_3 = domain_conf_variable_get($domain['domain_id'], 'stacks_search_exlibris_catalogue_url');
    } else {
      $catalogue_url_3 = variable_get('stacks_search_exlibris_catalogue_url');
    }
  } elseif ($stacks_search_external_3 == 'bibliocommons') {
    if (module_exists('domain_co233nf')) {
      $domain = domain_get_domain();
      $catalogue_url_3 = domain_conf_variable_get($domain['domain_id'], 'stacks_search_bibliocommons_catalogue_url');
    } else {
      $catalogue_url_3 = variable_get('stacks_search_bibliocommons_catalogue_url');
    }
  } elseif ($stacks_search_external_3 == 'vufind') {
    if (module_exists('domain_conf')) {
      $domain = domain_get_domain();
      $catalogue_url_3 = domain_conf_variable_get($domain['domain_id'], 'stacks_search_vufind_catalogue_url');
    } else {
      $catalogue_url_3 = variable_get('stacks_search_vufind_catalogue_url');
    }
  }

  $block['content'] = "<div class='region-header-search'>";
    $block['content'] .= "<!-- Search Area -->";
    $block['content'] .= "<form method='GET' id='globalSearch' action='' class='searchFor'>";
      $block['content'] .= "<h4>Find books, articles, videos and more...</h4>";
      $block['content'] .= "<div class='row'>";
        $block['content'] .= "<div class='large-8 columns searchBoxWrap'>";
          $block['content'] .= "<input type='text' value='". $query ."' placeholder='Find books, articles, videos and more...' title='Search' name='query' id='searchBox' class='text' />";
        $block['content'] .= "</div>";
        $block['content'] .= "<div class='large-2 columns selectSearchWrapper'>";
          $block['content'] .= "<select name='catalog' class='selectSearchCat'>";
            $block['content'] .= $catalogOptions;
          $block['content'] .= "</select>";
          $block['content'] .= "<span class='lbl-select'></span>";
        $block['content'] .= "</div>";
        $block['content'] .= "<div class='large-2 columns'>";
          $block['content'] .= "<input type='submit' value='Go' id='searchSubmit' class='submit' />";
        $block['content'] .= "</div>";
        //These hidden fields causes the exlibris search to break.
        if($stacks_search_external != 'exlibris') {
          $block['content'] .= "<input type='hidden' value='keyword' name='type' />";
          $block['content'] .= "<input type='hidden' value='1' name='pagenumber' />";
          $block['content'] .= "<input type='hidden' value='search' name='y' />";
        }
        //Required for III search
        if($stacks_search_external == 'iii') {
          $block['content'] .= "<input type='hidden' value='eng' name='lang' />";
        }
        //Required for exLibris search
        if($stacks_search_external == 'exlibris') {
          $block['content'] .= "<input type='hidden' value='search' name='fn' />";
        }
        if (!empty($stacks_search_external)) {
          $block['content'] .= "<input type='hidden' value='" . $catalogue_url . "' name='exturl' />";
        }
        if (!empty($stacks_search_external_2)) {
          $block['content'] .= "<input type='hidden' value='" . $catalogue_url_2 . "' name='exturl2' />";
        }
        if (!empty($stacks_search_external_3)) {
          $block['content'] .= "<input type='hidden' value='" . $catalogue_url_3 . "' name='exturl3' />";
        }
        if (!empty($stacks_search_external)) {
          $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_external', '')."' name='exttype' />";
          if ($stacks_search_external == 'edsnative') {
            if (!empty($native_auth_type)) {
              $block['content'] .= "<input type='hidden' value='".$native_auth_type."' name='eds_authtype' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_direct'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_direct')."' name='eds_direct' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_catalogue_url'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_catalogue_url')."' name='eds_catalogue_url' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_user'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_user')."' name='eds_user' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_pass'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_pass')."' name='eds_pass' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_scope'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_scope')."' name='eds_scope' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_profile'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_profile')."' name='eds_profile' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_org'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_org')."' name='eds_org' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_custid'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_custid')."' name='eds_custid' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_groupid'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_groupid')."' name='eds_groupid' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_site'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_site')."' name='eds_site' />";
            }
          }
          if ($stacks_search_external == 'edsnative2') {
            if (!empty($native_auth_type2)) {
              $block['content'] .= "<input type='hidden' value='".$native_auth_type2."' name='eds_authtype2' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_direct2'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_direct2')."' name='eds_direct2' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_catalogue_url2'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_catalogue_url2')."' name='eds_catalogue_url2' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_user2'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_user2')."' name='eds_user2' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_pass2'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_pass2')."' name='eds_pass2' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_scope2'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_scope2')."' name='eds_scope2' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_profile2'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_profile2')."' name='eds_profile2' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_org2'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_org2')."' name='eds_org2' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_custid2'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_custid2')."' name='eds_custid2' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_groupid2'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_groupid2')."' name='eds_groupid2' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_site2'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_site2')."' name='eds_site2' />";
            }
          }
          if ($stacks_search_external == 'edsnative3') {
            if (!empty($native_auth_type3)) {
              $block['content'] .= "<input type='hidden' value='".$native_auth_type3."' name='eds_authtype3' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_direct3'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_direct3')."' name='eds_direct3' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_catalogue_url3'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_catalogue_url3')."' name='eds_catalogue_url3' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_user3'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_user3')."' name='eds_user3' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_pass3'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_pass3')."' name='eds_pass3' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_scope3'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_scope3')."' name='eds_scope3' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_profile3'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_profile3')."' name='eds_profile3' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_org3'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_org3')."' name='eds_org3' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_custid3'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_custid3')."' name='eds_custid3' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_groupid3'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_groupid3')."' name='eds_groupid3' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_site3'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_site3')."' name='eds_site3' />";
            }
          }
        }
        if (!empty($stacks_search_external_2)) {
          $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_external_2', '')."' name='exttype2' />";
          if ($stacks_search_external_2 == 'edsnative') {
            if (!empty($native_auth_type)) {
              $block['content'] .= "<input type='hidden' value='".$native_auth_type."' name='eds_authtype' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_direct'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_direct')."' name='eds_direct' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_catalogue_url'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_catalogue_url')."' name='eds_catalogue_url' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_user'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_user')."' name='eds_user' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_pass'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_pass')."' name='eds_pass' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_scope'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_scope')."' name='eds_scope' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_profile'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_profile')."' name='eds_profile' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_org'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_org')."' name='eds_org' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_custid'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_custid')."' name='eds_custid' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_groupid'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_groupid')."' name='eds_groupid' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_site'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_site')."' name='eds_site' />";
            }
          }
          if ($stacks_search_external_2 == 'edsnative2') {
            if (!empty($native_auth_type2)) {
              $block['content'] .= "<input type='hidden' value='".$native_auth_type2."' name='eds_authtype2' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_direct2'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_direct2')."' name='eds_direct2' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_catalogue_url2'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_catalogue_url2')."' name='eds_catalogue_url2' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_user2'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_user2')."' name='eds_user2' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_pass2'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_pass2')."' name='eds_pass2' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_scope2'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_scope2')."' name='eds_scope2' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_profile2'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_profile2')."' name='eds_profile2' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_org2'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_org2')."' name='eds_org2' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_custid2'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_custid2')."' name='eds_custid2' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_groupid2'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_groupid2')."' name='eds_groupid2' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_site2'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_site2')."' name='eds_site2' />";
            }
          }
          if ($stacks_search_external_2 == 'edsnative3') {
            if (!empty($native_auth_type3)) {
              $block['content'] .= "<input type='hidden' value='".$native_auth_type3."' name='eds_authtype3' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_direct3'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_direct3')."' name='eds_direct3' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_catalogue_url3'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_catalogue_url3')."' name='eds_catalogue_url3' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_user3'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_user3')."' name='eds_user3' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_pass3'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_pass3')."' name='eds_pass3' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_scope3'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_scope3')."' name='eds_scope3' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_profile3'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_profile3')."' name='eds_profile3' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_org3'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_org3')."' name='eds_org3' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_custid3'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_custid3')."' name='eds_custid3' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_groupid3'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_groupid3')."' name='eds_groupid3' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_site3'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_site3')."' name='eds_site3' />";
            }
          }
        }
        if (!empty($stacks_search_external_3)) {
          $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_external_3', '')."' name='exttype3' />";
          if ($stacks_search_external_3 == 'edsnative') {
            if (!empty($native_auth_type)) {
              $block['content'] .= "<input type='hidden' value='".$native_auth_type."' name='eds_authtype' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_direct'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_direct')."' name='eds_direct' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_catalogue_url'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_catalogue_url')."' name='eds_catalogue_url' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_user'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_user')."' name='eds_user' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_pass'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_pass')."' name='eds_pass' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_scope'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_scope')."' name='eds_scope' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_profile'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_profile')."' name='eds_profile' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_org'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_org')."' name='eds_org' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_custid'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_custid')."' name='eds_custid' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_groupid'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_groupid')."' name='eds_groupid' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_site'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_site')."' name='eds_site' />";
            }
          }
          if ($stacks_search_external_3 == 'edsnative2') {
            if (!empty($native_auth_type2)) {
              $block['content'] .= "<input type='hidden' value='".$native_auth_type2."' name='eds_authtype2' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_direct2'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_direct2')."' name='eds_direct2' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_catalogue_url2'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_catalogue_url2')."' name='eds_catalogue_url2' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_user2'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_user2')."' name='eds_user2' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_pass2'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_pass2')."' name='eds_pass2' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_scope2'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_scope2')."' name='eds_scope2' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_profile2'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_profile2')."' name='eds_profile2' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_org2'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_org2')."' name='eds_org2' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_custid2'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_custid2')."' name='eds_custid2' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_groupid2'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_groupid2')."' name='eds_groupid2' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_site2'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_site2')."' name='eds_site2' />";
            }
          }
          if ($stacks_search_external_3 == 'edsnative3') {
            if (!empty($native_auth_type3)) {
              $block['content'] .= "<input type='hidden' value='".$native_auth_type3."' name='eds_authtype3' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_direct3'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_direct3')."' name='eds_direct3' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_catalogue_url3'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_catalogue_url3')."' name='eds_catalogue_url3' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_user3'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_user3')."' name='eds_user3' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_pass3'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_pass3')."' name='eds_pass3' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_scope3'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_scope3')."' name='eds_scope3' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_profile3'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_profile3')."' name='eds_profile3' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_org3'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_org3')."' name='eds_org3' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_custid3'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_custid3')."' name='eds_custid3' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_groupid3'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_groupid3')."' name='eds_groupid3' />";
            }
            if (!empty(variable_get('stacks_search_edsnative_site3'))) {
              $block['content'] .= "<input type='hidden' value='".variable_get('stacks_search_edsnative_site3')."' name='eds_site3' />";
            }
          }
        }
        $block['content'] .= "<input type='hidden' value='".base_path()."eds' name='edsurl' />";
        $block['content'] .= "<input type='hidden' value='".base_path()."multisearch' name='bento' />";
        $block['content'] .= "<input type='hidden' value='".base_path()."solr' name='web' />";
      $block['content'] .= "</div>";
    $block['content'] .= "</form>";
  $block['content'] .= "</div>";

  if ( (($stacks_search_external_checkbox == '1') || ($stacks_search_external_checkbox_2 == '1') || ($stacks_search_external_checkbox_3 == '1')) && (($stacks_search_external == 'polaris') || ($stacks_search_external_2 == 'polaris') || ($stacks_search_external_3 == 'polaris')) ) {
    $block['content'] .= "<object name=\"session_polaris\" style=\"visibility:hidden;\" data=\"".variable_get('stacks_search_polaris_catalogue_url')."\" width='1px' height='1px'></object>";
  }

  return $block;
}


// create custom filter to be used by the primary search view
function hf_history_filter_view($data) {
  $node_h = node_load($data->nid);
  $node_d = $node_h->field_history_date['und'][0]['value'];

  $return_d = true;
  $return_m = true;

  $day = strtotime($node_d);
  $day = date('d',$day);
  $day = (string)$day;
  if ($day == (string)date('d', time())) {
    $return_d = false;
  }

  $month = strtotime($node_d);
  $month = date('m',$month);
  $month = (string)$month;
  if ($month == (string)date('m', time())) {
    $return_m = false;
  }

  if (($return_d == false) && ($return_m == false)) {
    return false;
  } else {
    return true;
  }
}



