<?php
/**********************************************************
   Copyright (c) : Hybrid Forge 2014 . All Rights Reserved.
   Author: Jasen Maminski
 **********************************************************/

/**
 * Implementation of hook_menu().
 */
function hf_footer_menu() {

	$items['admin/config/stacks/footer'] = array(
		'title' => 'Footer Blocks',
		'description' => 'Selects and configure footer blocks settings',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('hf_footer_form'),
		'access arguments' => array('administer hf footer'),
		'file' => 'hf_footer.admin.inc',
	);
	return $items;
}

/*
 * Implementation of hook_permission().
 */
function hf_footer_permission() {
  return array(
	'administer hf footer' => array(
	  'title' => t('Administer HF Footer'),
	  'description' => t('Allows access to HF Footer admin page.'),
	),
  );
}

function hf_footer_menu_local_tasks_alter($data, $router_item, $root_path){

}

/**
 * Implementation of hook_theme().
 */
function hf_footer_theme() {
  return array(
		'hf_current_news_list' => array(
			'arguments' => array('form' => NULL),
			'file' => 'hf_footer.admin.inc',
			'render element' => null, // Hacked to removed notice, research in future how to do notices properly.
		),
  );
}

/**
 * Implementation of hook_block_info().
 */
function hf_footer_block_info() {
	$blocks = array();
	$blocks['hf_footer_contact'] = array(
		'info' => t('Footer Contact'),
		'cache' => DRUPAL_NO_CACHE,
	);
	$blocks['hf_footer_connect'] = array(
		'info' => t('Footer Connect'),
		'cache' => DRUPAL_NO_CACHE,
	);

	return $blocks;
}

/**
 * Implementation of hook_preprocess_block().
 * used to apply classes to footer blocks
 */
function hf_footer_preprocess_block(&$vars) {
  if ($vars['block_html_id'] == 'block-hf-footer-hf-footer-contact') {
	$vars['classes_array'][] = 'ft-contact';
  }
  if ($vars['block_html_id'] == 'block-hf-footer-hf-footer-connect') {
	$vars['classes_array'][] = 'ft-social';
  }
}

/**
 * Implementation of hook_block_view().
 */
function hf_footer_block_view($delta = '') {
	$module_path = drupal_get_path('module', 'hf_footer');
	$theme_path = path_to_theme();

	if (module_exists('domain_conf')) {
		$domain = domain_get_domain();

		$footer_txt = domain_conf_variable_get($domain['domain_id'], 'hf_footer_txt');
		$footer_twitter = domain_conf_variable_get($domain['domain_id'], 'hf_footer_twitter');
		$footer_facebook = domain_conf_variable_get($domain['domain_id'], 'hf_footer_facebook');
		$footer_flickr = domain_conf_variable_get($domain['domain_id'], 'hf_footer_flickr');
    $footer_youtube = domain_conf_variable_get($domain['domain_id'], 'hf_footer_youtube');

		$footer_gplus = domain_conf_variable_get($domain['domain_id'], 'hf_footer_gplus');
		$footer_instagram = domain_conf_variable_get($domain['domain_id'], 'hf_footer_instagram');
		$footer_linkedin = domain_conf_variable_get($domain['domain_id'], 'hf_footer_linkedin');
		$footer_pinterest = domain_conf_variable_get($domain['domain_id'], 'hf_footer_pinterest');
		$footer_tumblr = domain_conf_variable_get($domain['domain_id'], 'hf_footer_tumblr');

		$footer_email = domain_conf_variable_get($domain['domain_id'], 'hf_footer_email');
		$footer_staff = domain_conf_variable_get($domain['domain_id'], 'hf_footer_staff');
		$footer_directions = domain_conf_variable_get($domain['domain_id'], 'hf_footer_directions');
		$footer_locations = domain_conf_variable_get($domain['domain_id'], 'hf_footer_locations');

		$footer_phone = domain_conf_variable_get($domain['domain_id'], 'hf_footer_phone');
		$footer_phone2 = domain_conf_variable_get($domain['domain_id'], 'hf_footer_phone2');
		$footer_fax = domain_conf_variable_get($domain['domain_id'], 'hf_footer_fax');
		$footer_newsletter = domain_conf_variable_get($domain['domain_id'], 'hf_footer_newsletter');
	} else {
		$footer_txt = variable_get('hf_footer_txt');
		$footer_twitter = variable_get('hf_footer_twitter');
		$footer_facebook = variable_get('hf_footer_facebook');
    $footer_flickr = variable_get('hf_footer_flickr');
		$footer_youtube = variable_get('hf_footer_youtube');

		$footer_gplus = variable_get('hf_footer_gplus');
		$footer_instagram = variable_get('hf_footer_instagram');
		$footer_linkedin = variable_get('hf_footer_linkedin');
		$footer_pinterest = variable_get('hf_footer_pinterest');
		$footer_tumblr = variable_get('hf_footer_tumblr');

		$footer_email = variable_get('hf_footer_email');
		$footer_staff = variable_get('hf_footer_staff');
		$footer_directions = variable_get('hf_footer_directions');
		$footer_locations = variable_get('hf_footer_locations');

		$footer_phone = variable_get('hf_footer_phone');
		$footer_phone2 = variable_get('hf_footer_phone2');
		$footer_fax = variable_get('hf_footer_fax');
		$footer_newsletter = variable_get('hf_footer_newsletter');
	}

  // This example is adapted from node.module.
  $block = array();

  switch ($delta) {
	case 'hf_footer_contact':
				$block_content = "";
					$block_content .= "<p class='cpright'><span class='allrights'>Copyright &copy; ".date("Y").". All Rights Reserved.</span> <span class='poweredby'>Powered By <a href=\"http://stacksdiscovery.com/\" target=\"_blank\">Stacks</a> <small>".variable_get('stacks_version')."</small> | <a href=\"/user\">Staff Login</a></span></p>";
					$block_content .= "<div class='contact-icons'>";
						if ($footer_email) {
							$block_content .= "<a href=\"mailto:".$footer_email."\" class='fa fa-envelope-o'></a>&nbsp;";
						}
						if ($footer_staff) {
							$block_content .= "<a href=\"".$footer_staff."\" class='fa fa-user-o'></a>&nbsp;";
						}
						if ($footer_directions) {
							$block_content .= "<a href=\"".$footer_directions."\" class='fa fa-map-o'></a>&nbsp;";
						}
						if ($footer_locations) {
							$block_content .= "<a href=\"".$footer_locations."\" class='fa fa-dropbox'></a>&nbsp;";
						}
						if ($footer_newsletter) {
							$block_content .= "<a href=\"".$footer_newsletter."\" class='fa fa-newspaper-o'></a>&nbsp;";
						}
					$block_content .= "</div>";
					$block_content .= "<div class='contact-info'>";
						$block_content .= "<p>";
							if ($footer_phone) {
								$block_content .= "<a href=\"tel:+".$footer_phone."\">P. ".$footer_phone."</a>";
							}
							if ($footer_phone2) {
								if ($footer_phone) {
									$block_content.= " | ";
								}
								$block_content .= "<a href=\"tel:+".$footer_phone2."\">P. ".$footer_phone2."</a>";
							}
							if ($footer_fax) {
								if ($footer_phone || $footer_phone2) {
									$block_content.= " | ";
								}
								$block_content .= "<a href=\"tel:+".$footer_fax."\">F. ".$footer_fax."</a>";
							}
						$block_content .= "</p>";
					$block_content .= "</div>";

				$block['content'] = $block_content;
				$block['title'] = '<none>';
	  break;

	case 'hf_footer_connect':
			$block_connect = "";
			$block_connect .= "<div class=\"social-footer\">";
				if ($footer_facebook) {
					$block_connect .= "<a href=\"".$footer_facebook."\" target=\"_blank\" class='fa fa-facebook-square'></a>&nbsp;";
				}
				if ($footer_twitter) {
					$block_connect .= "<a href=\"".$footer_twitter."\" target=\"_blank\" class='fa fa-twitter-square'></a>&nbsp;";
				}
				if ($footer_txt) {
					$block_connect .= "<a href=\"".$footer_txt."\" target=\"_blank\" class='fa fa-twitter-square'></a>&nbsp;";
				}
				if ($footer_youtube) {
					$block_connect .= "<a href=\"".$footer_youtube."\" target=\"_blank\" class='fa fa-youtube-square'></a>&nbsp;";
				}
        if ($footer_flickr) {
          $block_connect .= "<a href=\"".$footer_flickr."\" target=\"_blank\" class='fa fa-flickr'></a>&nbsp;";
        }
				if ($footer_gplus) {
					$block_connect .= "<a href=\"".$footer_gplus."\" target=\"_blank\" class='fa fa-google-plus-square'></a>&nbsp;";
				}
				if ($footer_instagram) {
					$block_connect .= "<a href=\"".$footer_instagram."\" target=\"_blank\" class='fa fa-instagram'></a>&nbsp;";
				}
				if ($footer_linkedin) {
					$block_connect .= "<a href=\"".$footer_linkedin."\" target=\"_blank\" class='fa fa-linkedin-square'></a>&nbsp;";
				}
				if ($footer_pinterest) {
					$block_connect .= "<a href=\"".$footer_pinterest."\" target=\"_blank\" class='fa fa-pinterest-square'></a>&nbsp;";
				}
				if ($footer_tumblr) {
					$block_connect .= "<a href=\"".$footer_tumblr."\" target=\"_blank\" class='fa fa-tumblr-square'></a>&nbsp;";
				}
				$block_connect .= "</div>";
			$block['content'] = $block_connect;
			$block['title'] = '<none>';
	 break;
  }
  return $block;
}
