<?php
/**
 * Implementation of hook_block_info().
 */
function hf_basic_search_block_info() {
  $blocks = array();
  $blocks['hf_basic_search'] = array(
    'info' => t('Stacks Basic Search'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implementation of hook_block_view().
 */
function hf_basic_search_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'hf_basic_search':
      $block['subject'] = '';
      $block['content'] = drupal_get_form('hf_basic_search_form');
      break;
  }

  return $block;
}

function hf_basic_search_form($form, &$form_state) {
  $form = array(
    '#theme_wrappers' => array('form')
  );

  $form['#action'] = '/solr';
  $form['#method'] = 'get';

  $form['bentoq'] = array(
    '#type' => 'textfield',
    '#title' => '',
    '#theme_wrappers' => array(),
    '#default_value' => ''
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Search',
    '#theme_wrappers' => array(),
    '#attributes' => array('class' => array('btn-request'))
  );

  return $form;
}

// save the rating
function hf_basic_search_form_submit($form, &$form_state) {
  //$form_state = $form_state['values'];
  //drupal_goto('solr?bentoq='.$form_state['query']);
}

function hf_basic_search_theme($existing, $type, $theme, $path) {
  $items['hf_basic_search_form'] = array(
    'render element' => 'form',
    'template' => 'templates/hf_basic_search',
    'path' => drupal_get_path('module', 'hf_basic_search') . '',
  );

  return $items;
}