<?php

/**
 * Implements  hook_form_BASE_FORM_ID_alter().
 */
/*
function hf_overrides_form_node_form_alter(&$form, $form_state) {
  $node = $form['#node'];
  if (variable_get('custom_breadcrumbs_show_form_table_' . $node->type, CUSTOM_BREADCRUMBS_SHOW_FORM_TABLE_DEFAULT) && user_access('administer custom breadcrumbs')) {
    $form['custom_breadcrumbs']['#title'] = t('Custom breadcrumbs');
  }
}
*/

function hf_overrides_menu_local_tasks_alter(&$data) {
  $adminRole = false;
  global $user;
  if (in_array('super administrator', $user->roles)) {
    $adminRole = true;
  }

  if ($adminRole == false) {
    // remove sub menu for themes settings for non-super admins
    if (strpos(current_path(), 'admin/appearance/settings') !== false) {
      foreach ($data['tabs'][0]['output'] as $key => $value) {
        unset($data['tabs'][0]['output'][$key]);
      }
      foreach ($data['tabs'][1]['output'] as $key => $value) {
          unset($data['tabs'][1]['output'][$key]);
      }
    }
    // re-direct non-super admin user to sanitised theme page
    if (current_path() == 'admin/appearance') {
      drupal_goto('admin/config/stacks/themes');
    }
  }
}

function hf_overrides_form_alter(&$form, &$form_state, $form_id) {
  if($form_id == 'search_block_form') {
    if ($form['#id'] == 'search-block-form--2') {
      $form['search_block_form']['#required'] = true;
      $form['search_block_form']['#attributes']['required'] = 'required';
    }
  }
  if($form_id == 'callout_node_form') {
    $form['field_cta1_title'][LANGUAGE_NONE][0]['value']['#maxlength'] = 60;
    $form['field_cta2_title'][LANGUAGE_NONE][0]['value']['#maxlength'] = 60;
    $form['field_cta3_title'][LANGUAGE_NONE][0]['value']['#maxlength'] = 60;
    $form['field_cta4_title'][LANGUAGE_NONE][0]['value']['#maxlength'] = 60;
  }
}


// init hook
function hf_overrides_init() {
  // redirect patron if they land on the admin dashboard after login redirect
  $currentURL = request_uri();
  if ($currentURL == "/admin/dashboard") {
    $user_role = $GLOBALS['user']->roles;

    if (!empty($user_role)) {
      foreach ($user_role as $role) {
        if ($role == 'patron') {
          drupal_goto('/my-account');
        }
      }
    }
  }
}

// Override menu items
function hf_overrides_menu_alter(&$items){
  $items['admin/appearance']['title'] = 'My Theme';
  $items['admin/appearance/settings/hfstacks']['title'] = 'Stacks Basic';
  $items['admin/config/stacks/footer']['title'] = 'Social Media';
  $items['admin/structure/taxonomy']['title'] = 'Taxonomies';
}

function hf_overrides_form_search_form_alter(&$form, &$form_state) {
  // Remove the search form from search result page
  if ((arg(1) == 'node') && (arg(2) != NULL)) {
    $form['#access'] = FALSE;
  }
}

// used for making uploaded files permanent for theme uploads
function _fix_permanent_file($image, $theme) {
  $fid = theme_get_setting($image, $theme);
  if ($fid > 0) {
    $file = file_load($fid);
    if (is_object($file) && $file->status == 0) {
      $file->status = FILE_STATUS_PERMANENT;
      file_save($file);
      file_usage_add($file, $theme, 'theme', 1);
    }
  }
}