<?php
/*
 * Stacks pages allows the creation and management of landing pages for use with Panels
 */


/**
 * Implements hook_menu()
 *
 * @return array
 */
function hf_stacks_pages_menu() {
	$items = array();

  $items['admin/landing-pages'] = array(
    'title' => 'Stacks Landing Pages',
    'page callback' => 'hf_stacks_pages_list',
    'access arguments' => array('administer stacks config'),
    'type' => MENU_CALLBACK,
    'file' => 'hf_stacks_pages.page.inc',
  );
  $items['admin/landing-pages/add'] = array(
    'title' => 'Stacks Landing Pages',
    'description' => 'Create a new landing page.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('hf_stacks_pages_add'),
    'access arguments' => array('administer stacks config'),
    'type' => MENU_CALLBACK,
    'file' => 'hf_stacks_pages.admin.inc',
  );
  $items['admin/landing-pages/edit/%'] = array(
    'title' => 'Stacks Landing Pages',
    'description' => 'Edit a current landing page.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('hf_stacks_pages_edit'),
    'access arguments' => array('administer stacks config'),
    'type' => MENU_CALLBACK,
    'file' => 'hf_stacks_pages.admin.inc',
  );
  $items['admin/landing-pages/delete/%'] = array(
    'title' => 'Stacks Landing Pages',
    'description' => 'Delete a current landing page.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('hf_stacks_pages_delete'),
    'access arguments' => array('administer stacks config'),
    'type' => MENU_CALLBACK,
    'file' => 'hf_stacks_pages.admin.inc',
  );

	return $items;
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function hf_stacks_pages_ctools_plugin_directory($module, $plugin) {
  if (($module == 'ctools' || $module == 'panels') && !empty($plugin)) {
    return 'plugins/' . $plugin;
  }
}