<?php
/**
 * Implements hook_permission().
 */
function hf_themes_permission() {
  return array(
    'stacks themes' => array(
      'title' => t('Administer Stacks Themes'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function hf_themes_menu() {
  $items['admin/config/stacks/themes'] = array(
    'title' => 'Stacks Themes',
    'description' => 'Configure theme selection settings.',
    'access arguments' => array('stacks themes'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('hf_themes_admin_form'),
  );

  return $items;
}

function hf_themes_admin_form($node, &$form_state) {
  global $base_url;
  $form = array();
  $options = hf_themes_options();
  $themes = array();

  foreach ($options as $stacks_theme => $label) {
    $themes[$label['machine']] = '<p class="ttl">'.$label['name'].'</p><p class="img"><img src="'.$base_url.'/'.$label['screenshot'].'"/></p><p class="settings-panel"><a class="waves-effect waves-button waves-classic" href="'.$base_url.'/admin/appearance/settings/'.$label['machine'].'">Settings</a></p>';
  }

  $form['submit'] = array(
    '#type'     => 'submit',
    '#value'    => 'Activate Theme',
    // '#suffix'   => '<div class="upcoming-themes">' .
    // '<h2>Upcoming themes</h2>' .
    // '<div class="form-item form-type-radio form-item-themes">' .
    // '<p class="ttl">Clear Fog</p>' .
    // '<p class="img"><img src="'.$base_url.'/sites/all/modules/hf_stacks/hf_themes/screenshot-fog.png"></p>' .
    // '</div>' .
    // '<div class="form-item form-type-radio form-item-themes">' .
    // '<p class="ttl">Crayons</p>' .
    // '<p class="img"><img src="'.$base_url.'/sites/all/modules/hf_stacks/hf_themes/screenshot-colors.png"></p>' .
    // '</div>' .
    // '</div>',
  );

  $form['themes'] = array(
    '#type' => 'radios',
    // '#title' => 'Active Theme',
    '#prefix' => '<div class="active-theme-panel">',
    '#suffix' =>

     '<div class="form-item form-type-radio form-item-themes coming-soon">' .
     '<p class="ttl">Mosaic</p>' .
     '<p class="img"><img src="'.$base_url.'/sites/all/modules/hf_stacks/hf_themes/screenshot-mosaic.png"></p>' .
     '<p class="settings-panel"><span>Coming Soon</span></p>' .
     '</div>' .
     '</div>' .

    '</div>',
    '#options' => $themes,
    '#default_value' => variable_get('theme_default'),
  );


  return $form;
}

/**
 * Form submission handler
 */
function hf_themes_admin_form_submit($form, &$form_state) {
  $form_state['rebuild'] = TRUE;

  variable_set('theme_default',$form_state['values']['themes']);

  drupal_flush_all_caches();

  drupal_set_message('Theme setting have been updated.');
}

/**
 * Returns an #options list of enabled themes.
 */
function hf_themes_options() {
  $options = array();
  $themes = list_themes();
  foreach ($themes as $stacks_theme => $theme) {
    //dpm($theme);
    if ($theme->status) {
      if ($theme->name != 'adminimal') {
        $options[$stacks_theme]['machine'] = $theme->name;
        $options[$stacks_theme]['name'] = $theme->info['name'];
        $options[$stacks_theme]['screenshot'] = $theme->info['screenshot'];
      }
    }
  }
  return $options;
}

/**
 * Returns hf_themes_options() with customized theme labels.
 */
function hf_themes_select() {
  $options = array();
  foreach (hf_themes_options() as $name => $label) {
    $options[$name] = variable_get('hf_themes_' . $label, $label);
  }
  asort($options);

  return $options;
}