<?php

/**
 * Implements hook_help()
 */
function hf_stacks_help($path, $arg) {
	switch ($path) {
		case "admin/help#elephant_base":
			$form = 'Help';
			return $form;
			break;
	}
}

/**
 * Implementation of hook_permission()
 */
function hf_stacks_permission(){
	return array(
		'administer stacks config' => array(
			'title' => t('Administer HF Stacks'),
			'description' => t('Administer HF Stacks Configuration.'),
		),
		'access patron' => array(
			'title' => t('Access patron features'),
			'description' => t('Access patron features.'),
		),
		'view stacks dashboard' => array(
			'title' => t('View HF Stacks Dashboard'),
			'description' => t('View HF Stacks Dashboard.'),
		),
		'administer custom css' => array(
			'title' => t('Administer custom css'),
			'description' => t('Administer custom css settings.'),
		),
	);
}

/**
 * Implements hook_menu().
 */
function hf_stacks_menu() {

	$items = array();
	$items['admin/config/stacks'] = array(
		'title' => 'HF Stacks',
		'description' => 'Elephant System Management',
		'position' => 'right',
		'weight' => -50,
		'page callback' => 'system_admin_menu_block_page',
		'access arguments' => array('administer stacks config'),
		'file' => 'system.admin.inc',
		'file path' => drupal_get_path('module', 'system'),
	);

	return $items;
}

/**
 * Implementation of hook_block_info().
 */

function hf_stacks_block_info() {
	$blocks = array();
	$blocks['hf_stacks_login'] = array(
		'info' => t('Patron Login'),
		'cache' => DRUPAL_NO_CACHE,
	);

	$blocks['hf_stacks_account'] = array(
		'info' => 'Account Snapshot',
		'cache' => DRUPAL_NO_CACHE,
	);
	return $blocks;
}


/**
 * Implementation of hook_block_view().
 */
function hf_stacks_block_view($delta='') {
	if($delta == 'hf_stacks_login' && !user_is_logged_in()) {
		$block = array();
		$block['subject'] = t('Patron Login');

		if (module_exists("hf_stacks_auth")) {
			$block['content'] = drupal_get_form('_hf_stacks_patron_login_block_form');
		} else {
			$block['content'] = "Auth module must be enabled";
		}
		return $block;
	}

	if($delta == 'hf_stacks_login') {  //&& patron_login_is_logged_in()
		$block = array();
		$block['subject'] = t('My Account');
		$block['content'] = 'You are now logged in.';
		return $block;
	}
}


/**
 * Implements hook_form()
 *
 * @param $form
 * @param $form_state
 * @return array
 */
function _hf_stacks_patron_login_block_form($form, &$form_state) {
	$form = array();

	$form['barcode'] = array(
		'#type' => 'textfield',
		'#title' => t('Library Card Number'),
		'#maxlength' => 32,
		'#size' => 15,
		'#required' => TRUE,
	);
	$form['pass'] = array(
		'#type' => 'password',
		'#title' => t('Pin'),
		'#maxlength' => 32,
		'#size' => 15,
		'#required' => TRUE,
	);
  $form['bibid'] = array(
    '#type' => 'hidden',
    '#default_value' => '',
    '#attributes' => array(
      'id' => 'bib-id',
    )
  );

	$form['submit'] = array(
    '#type' => 'submit',
		'#value' => t('Log in'),
	);
	$form['staffLogin'] = array(
    '#type' => 'markup',
    '#prefix' => '<a href="/?q=user" class="link-staff-login">',
		'#markup' => t('Staff Login'),
		'#suffix' => '</a>',
	);

	return $form;
}

function _hf_stacks_patron_login_block_form_submit($form, &$form_state) {
	if (module_exists('hf_stacks_auth')) {
		hf_stacks_auth_login($form_state['values']);
	} else {
		drupal_set_message('Please enable Stacks Authentication module.');
	}
}