<?php

/*
 * Implements hook_block_info().
 */
function hf_searchsave_block_info(){
	$blocks = array();
	$blocks['searchsave'] = array(
		'info' => t('HF Saved Searches'),
	);
	return $blocks;
}


/*
 * Implements hook_block_view().
 */
function hf_searchsave_block_view($delta = '') {
	$block = array();
	$similarString = '';

	global $base_url;

	switch($delta) {
		case 'searchsave': {
      $user = $GLOBALS['user'];
      $uid = $user->uid;

			$query = db_select('stacks_searchlist', 's');
			$query->fields('s', array('title'));
			$query->fields('s', array('url'));
			$query->condition('s.uid',$uid,'=');
			$results = $query->execute();

			$savedSearches = '';
			$savedSearches .= "<h2>Saved Searches</h2>";
      $savedSearches .= '<div class="fixed-menu">';
      $savedSearches .= "<ul>";

			while($record = $results->fetchAssoc()) {
				// get saved searches for this user
        $savedSearches .= "<li>";
          $savedSearches .= "<a href=\"".$record["url"]."\">".$record["title"]."</a>";
        $savedSearches .= "</li>";
			}

      $savedSearches .= "</ul>";
      $savedSearches .= '</div>';

      $block['content'] = $savedSearches;
    }
    break;
  }
	return $block;
}