<?php

/**
	* Implements hook_menu()
	*
	* @return array
	* Page Arguments Format
	* $var_type = node type/content type machine name
	* $add_content_path = add content path
  * $page_title = page title
	* $btn_label = button label
	* $url_path =  url path
	*/

function hf_dashboard_views_menu() {
  $menu = array();
  // Build Callout
  // Page Arguments: $var_type = node type/content type machine name, $add_content_path = add content path, $page_title = page title, $btn_label = button label, $url_path =  url path, workflow status, special columns
  $menu['admin/content/callouts'] = array(
    'title' => 'Callouts',
    'page callback' => 'hf_dashboard_views_page_callback',
    'page arguments' => array('callout', 'callout', 'Callouts', 'Add New', 'admin/content/callouts', TRUE, ''),
    'access arguments' => array('view stacks dashboard'),
    'type' => MENU_CALLBACK,
    'file' => 'hf_dashboard_views_tpl.inc',
  );

  // Build Directory Listing
  // Page Arguments: $var_type = node type/content type machine name, $add_content_path = add content path, $page_title = page title, $btn_label = button label, $url_path =  url path, workflow status, special columns
  $menu['admin/content/directory-listings'] = array(
    'title' => 'Directory Listings',
    'page callback' => 'hf_dashboard_views_page_callback',
    'page arguments' => array('directory_listing', 'directory-listing', 'Directory Listings', 'Add New', 'admin/content/directory-listings', TRUE, ''),
    'access arguments' => array('view stacks dashboard'),
    'type' => MENU_CALLBACK,
    'file' => 'hf_dashboard_views_tpl.inc',
  );

  // Build Database listing
  // Page Arguments: $var_type = node type/content type machine name, $add_content_path = add content path, $page_title = page title, $btn_label = button label, $url_path =  url path, workflow status, special columns
  $menu['admin/content/database-listings'] = array(
    'title' => 'Database Listings',
    'page callback' => 'hf_dashboard_views_page_callback',
    'page arguments' => array('e_resource', 'e-resource', 'Database Listings', 'Add New', 'admin/content/database-listings', FALSE, ''),
    'access arguments' => array('view stacks dashboard'),
    'type' => MENU_CALLBACK,
    'file' => 'hf_dashboard_views_tpl.inc',
  );

  // Build Research Guide
  // Page Arguments: $var_type = node type/content type machine name, $add_content_path = add content path, $page_title = page title, $btn_label = button label, $url_path =  url path, workflow status, special columns
  $menu['admin/content/research-guides'] = array(
    'title' => 'Research Guides',
    'page callback' => 'hf_dashboard_views_page_callback',
    'page arguments' => array('guide', 'guide', 'Research Guides', 'Add New', 'admin/content/research-guides', TRUE, ''),
    'access arguments' => array('view stacks dashboard'),
    'type' => MENU_CALLBACK,
    'file' => 'hf_dashboard_views_tpl.inc',
  );

  // Build Resource Flow
  // Page Arguments: $var_type = node type/content type machine name, $add_content_path = add content path, $page_title = page title, $btn_label = button label, $url_path =  url path, workflow status, special columns
  $menu['admin/content/resource-flows'] = array(
    'title' => 'Resource Flows',
    'page callback' => 'hf_dashboard_views_page_callback',
    'page arguments' => array('resource_list', 'resource-list', 'Resource Flows', 'Add New', 'admin/content/resource-flows', TRUE, ''),
    'access arguments' => array('view stacks dashboard'),
    'type' => MENU_CALLBACK,
    'file' => 'hf_dashboard_views_tpl.inc',
  );

  // Build Location and Hours
  // Page Arguments: $var_type = node type/content type machine name, $add_content_path = add content path, $page_title = page title, $btn_label = button label, $url_path =  url path, workflow status, special columns
  $menu['admin/content/locations-and-hours'] = array(
    'title' => 'Locations & Hours',
    'page callback' => 'hf_dashboard_views_page_callback',
    'page arguments' => array('library_branch', 'library-branch', 'Locations & Hours', 'Add New', 'admin/content/locations-and-hours', FALSE, ''),
    'access arguments' => array('view stacks dashboard'),
    'type' => MENU_CALLBACK,
    'file' => 'hf_dashboard_views_tpl.inc',
  );

  // Build News Articles
  // Page Arguments: $var_type = node type/content type machine name, $add_content_path = add content path, $page_title = page title, $btn_label = button label, $url_path =  url path, workflow status, special columns
  $menu['admin/content/news-articles'] = array(
    'title' => 'News Articles',
    'page callback' => 'hf_dashboard_views_page_callback',
    'page arguments' => array('news', 'news', 'News Articles', 'Add New', 'admin/content/news-articles', TRUE, ''),
    'access arguments' => array('view stacks dashboard'),
    'type' => MENU_CALLBACK,
    'file' => 'hf_dashboard_views_tpl.inc',
  );

  // Build Events
  // Page Arguments: $var_type = node type/content type machine name, $add_content_path = add content path, $page_title = page title, $btn_label = button label, $url_path =  url path, workflow status, special columns
  $menu['admin/content/events'] = array(
    'title' => 'Events',
    'page callback' => 'hf_dashboard_views_page_callback',
    'page arguments' => array('event', 'event', 'Events', 'Add New', 'admin/content/events', TRUE, ''),
    'access arguments' => array('view stacks dashboard'),
    'type' => MENU_CALLBACK,
    'file' => 'hf_dashboard_views_tpl.inc',
  );

  // Build Easy Forms
  // Page Arguments: $var_type = node type/content type machine name, $add_content_path = add content path, $page_title = page title, $btn_label = button label, $url_path =  url path, workflow status, special columns
  $menu['admin/content/easy-forms'] = array(
    'title' => 'Easy Forms',
    'page callback' => 'hf_dashboard_views_page_callback',
    'page arguments' => array('webform', 'webform', 'Easy Forms', 'Add New', 'admin/content/easy-forms', FALSE, ''),
    'access arguments' => array('view stacks dashboard'),
    'type' => MENU_CALLBACK,
    'file' => 'hf_dashboard_views_tpl.inc',
  );

  // Build Sliders and Mini Slider
  // Page Arguments: $var_type = node type/content type machine name, $add_content_path = add content path, $page_title = page title, $btn_label = button label, $url_path =  url path, workflow status, special columns
  $menu['admin/content/sliders'] = array(
    'title' => 'Sliders',
    'page callback' => 'hf_dashboard_views_page_callback',
    'page arguments' => array('slider', 'slider', 'Sliders', 'Add New Slider', 'admin/content/sliders', TRUE, ''),
    'access arguments' => array('view stacks dashboard'),
    'type' => MENU_CALLBACK,
    'file' => 'hf_dashboard_views_tpl.inc',
  );

  // Build Reserves Lists
  // Page Arguments: $var_type = node type/content type machine name, $add_content_path = add content path, $page_title = page title, $btn_label = button label, $url_path =  url path, workflow status, special columns
  $menu['admin/content/reserves-listings'] = array(
    'title' => 'Reserves Listings',
    'page callback' => 'hf_dashboard_views_page_callback',
    'page arguments' => array('reserves', 'reserves', 'Reserves Listings', 'Add New', 'admin/content/reserves-listings', TRUE, ''),
    'access arguments' => array('view stacks dashboard'),
    'type' => MENU_CALLBACK,
    'file' => 'hf_dashboard_views_tpl.inc',
  );

  // Build Days in History
  // Page Arguments: $var_type = node type/content type machine name, $add_content_path = add content path, $page_title = page title, $btn_label = button label, $url_path =  url path, workflow status, special columns
  $menu['admin/content/days-in-history'] = array(
    'title' => 'Days in History',
    'page callback' => 'hf_dashboard_views_page_callback',
    'page arguments' => array('history', 'history', 'Days in History', 'Add New', 'admin/content/days-in-history', TRUE, ''),
    'access arguments' => array('view stacks dashboard'),
    'type' => MENU_CALLBACK,
    'file' => 'hf_dashboard_views_tpl.inc',
  );

  // Build Static Content
  // Page Arguments: $var_type = node type/content type machine name, $add_content_path = add content path, $page_title = page title, $btn_label = button label, $url_path =  url path, workflow status, special columns
  $menu['admin/content/static-content'] = array(
    'title' => 'Static Content',
    'page callback' => 'hf_dashboard_views_page_callback',
    'page arguments' => array('page', 'page', 'Static Content', 'Add New', 'admin/content/static-contents', TRUE, ''),
    'access arguments' => array('view stacks dashboard'),
    'type' => MENU_CALLBACK,
    'file' => 'hf_dashboard_views_tpl.inc',
  );

  // Build RSS Items
  // Page Arguments: $var_type = node type/content type machine name, $add_content_path = add content path, $page_title = page title, $btn_label = button label, $url_path =  url path, workflow status, special columns
  $menu['admin/content/rss-items'] = array(
    'title' => 'RSS Feeds',
    'page callback' => 'hf_dashboard_views_page_callback',
    'page arguments' => array('rss_item', 'rss-item', 'RSS Item', 'Add New', 'admin/content/rss-item', TRUE, ''),
    'access arguments' => array('view stacks dashboard'),
    'type' => MENU_CALLBACK,
    'file' => 'hf_dashboard_views_tpl.inc',
  );

  /*
  // Build Reservation Rooms
  // Page Arguments: $var_type = node type/content type machine name, $add_content_path = add content path, $page_title = page title, $btn_label = button label, $url_path =  url path, workflow status, special columns
  $menu['admin/roombooking/rooms'] = array(
    'title' => 'Booking Rooms',
    'page callback' => 'hf_dashboard_views_page_callback',
    'page arguments' => array('room_roombookings_room', 'room-roombookings-room', 'Room Booking Room', 'Add New', 'admin/booking/room', FALSE, ''),
    'access arguments' => array('view stacks dashboard'),
    'type' => MENU_CALLBACK,
    'file' => 'hf_dashboard_views_tpl.inc',
  );

  // Build Reservation Categories
  // Page Arguments: $var_type = node type/content type machine name, $add_content_path = add content path, $page_title = page title, $btn_label = button label, $url_path =  url path, workflow status, special columns
  $menu['admin/roombooking/groups'] = array(
    'title' => 'Booking Categories',
    'page callback' => 'hf_dashboard_views_page_callback',
    'page arguments' => array('room_roombookings_category', 'room-roombookings-group', 'Room Booking Group', 'Add New', 'admin/booking/group', FALSE, 'roombooking_capacity,reservation_group'),
    'access arguments' => array('view stacks dashboard'),
    'type' => MENU_CALLBACK,
    'file' => 'hf_dashboard_views_tpl.inc',
  );

  // Build Reservation Reservations
  // Page Arguments: $var_type = node type/content type machine name, $add_content_path = add content path, $page_title = page title, $btn_label = button label, $url_path =  url path, workflow status, special columns
  $menu['admin/roombooking/reservations'] = array(
    'title' => 'Booking Reservations',
    'page callback' => 'hf_dashboard_views_page_callback',
    'page arguments' => array('room_roombookings_reservation', 'room-roombookings-reservation', 'Room Booking Reservation', 'Add New', 'admin/booking/reservation', FALSE, 'roombooking_room;roombooking_date'),
    'access arguments' => array('view stacks dashboard'),
    'type' => MENU_CALLBACK,
    'file' => 'hf_dashboard_views_tpl.inc',
  );
  */

  /*
  // Menu page
  $menu['admin/content/menus'] = array(
    'title' => 'Menus',
    'page callback' => 'hf_dashboard_menu_page_callback',
    // 'page arguments' => array(''),
    'access arguments' => array('view stacks dashboard'),
    'type' => MENU_CALLBACK,
    'file' => 'hf_dashboard_menu_tpl.inc',
  );
  */

  return $menu;
}
