<?php

/**
 * Implements hook_module()
 *
 * @return array
 */
function studyroom_email_menu() {
  $items = array();
  $items['admin/roombooking/email'] = array(
    'title' => 'Room Booking Emails',
    'description' => 'Manage Room Booking Email Templates',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('studyroom_email_form'),
    'access arguments' => array('administer stacks config'),
    'file' => 'studyroom_email.admin.inc'
  );
  return $items;
}

function studyroom_email_mail($from = 'default_from', $to, $subject, $message) {
  $my_module = 'studyroom_email';
  $my_mail_token = microtime();
  if ($from == 'default_from') {
    // Change this to your own default 'from' email address.
    $from = variable_get('system_mail', 'info@stacksdiscovery.com');
  }
  $message = array(
    'id' => $my_module . '_' . $my_mail_token,
    'to' => $to,
    'subject' => $subject,
    'body' => array($message),
    'headers' => array(
      'From' => $from,
      'Sender' => $from,
      'Return-Path' => $from,
    ),
  );
  $system = drupal_mail_system($my_module, $my_mail_token);
  $message = $system->format($message);
  if ($system->mail($message)) {
    return TRUE;
  } else {
    return FALSE;
  }

  // Email Sending Usage
  /*
    $user = user_load($userid); // load a user using its uid
    $usermail = (string) $user->mail; // load user email address
    studyroom_email_mail('default_from', $usermail, 'THIS IS THE SUBJECT', 'THIS IS THE EMAIL BODY');
   */
}

/**
 * Implements hook_cron()
 */
function studyroom_email_cron() {
  $email_days = variable_get('studyroom_email_booking_reminder_cron_days');
  $email_time = variable_get('studyroom_email_booking_reminder_cron_time');

  $timestamp = REQUEST_TIME;
  $day_current = date("Y-m-d",$timestamp);
  $day_future = DateTime::createFromFormat('Y-m-d',$day_current);
  $day_future->modify('+'.$email_days.' days');
  $day_future = $day_future->format('Y-m-d');
  $time_current = date("g A",$timestamp);

  if ($time_current == $email_time) {
    $email_from = variable_get('studyroom_email_booking_reminder_address');
    $email_subject = variable_get('studyroom_email_booking_reminder_subject');
    $email_body = variable_get('studyroom_email_booking_reminder');

    $query = db_select('studyroom_reservation', 'r');
    $query->leftJoin('studyroom_space', 's', 's.space_id = r.space_id');
    $query->leftJoin('field_data_field_reservation_datetime', 'd', 'd.entity_id = r.space_id');
    $query->leftJoin('field_data_field_reservation_contact_phone', 'p', 'p.entity_id = r.space_id');
    $query->leftJoin('field_data_field_reservation_contact_name', 'n', 'n.entity_id = r.space_id');
    $query->leftJoin('field_data_field_reservation_contact_email', 'e', 'e.entity_id = r.space_id');
    $query->leftJoin('field_data_field_reservation_contact_desc', 'v', 'v.entity_id = r.space_id');
    $query->leftJoin('field_data_field_reservation_datetime', 't', 't.entity_id = r.space_id');
    $query->leftJoin('field_data_field_reservation_occupancy', 'o', 'o.entity_id = r.space_id');
    $query->fields('r', array('reservation_id','space_id','duration'));
    $query->fields('s', array('label','capacity','type'));
    $query->fields('d', array('field_reservation_datetime_value'));
    $query->fields('p', array('field_reservation_contact_phone_number'));
    $query->fields('n', array('field_reservation_contact_name_value'));
    $query->fields('e', array('field_reservation_contact_email_email'));
    $query->fields('v', array('field_reservation_contact_desc_value'));
    $query->fields('t', array('field_reservation_datetime_value'));
    $query->fields('o', array('field_reservation_occupancy_value'));
    $query->execute();

    $reservations = $query->execute()->fetchAll();

    foreach ($reservations as $reservation) {
      $time_start = $reservation->field_reservation_datetime_value ?: '';
      $duration = $reservation->duration ?: '';
      $occupancy = $reservation->field_reservation_occupancy_value ?: '';
      $contact_desc = $reservation->field_reservation_contact_desc_value ?: '';
      $contact_name = $reservation->field_reservation_contact_name_value ?: '';
      $contact_email = $reservation->field_reservation_contact_email_email ?: '';
      $contact_phone = $reservation->field_reservation_contact_phone_number ?: '';
      $room = $reservation->label ?: '';
      $group = $reservation->type ?: '';

      $lookup = array(
        "%datetime%" => date('l jS \of F Y g:i:s A',strtotime($time_start)),
        "%duration%" => $duration.' hours',
        "%occupancy%" => $occupancy,
        "%description%" => $contact_desc,
        "%name%" => $contact_name,
        "%email%" => $contact_email,
        "%phone%" => $contact_phone,
        "%room%" => $room,
        "%group%" => $group,
      );
      $email_body = strtr($email_body,$lookup);

      if ($day_future == date("Y-m-d",strtotime($time_start))) {
        studyroom_email_mail($email_from, $contact_email, $email_subject, $email_body);
        //error_log(print_r($email_body, TRUE));
      }
    }
  }
}